In [1]:
!pip install tensorflow_text

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
import numpy as np
import pandas as pd

##Getting to know about BERT

In [3]:
preprocess_url='https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

model_url='https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'

In [4]:
bert_preprocess_url=hub.KerasLayer(preprocess_url)

In [5]:
analyze_text=['I like python programming','This is a deep learning class','All my colleagues like deep learning']

In [6]:
preprocess_text = bert_preprocess_url(analyze_text)

In [7]:
preprocess_text.keys()

dict_keys(['input_mask', 'input_type_ids', 'input_word_ids'])

In [8]:
preprocess_text['input_mask']


# CLS I like python programming SEP


#CLS All my colleagues like deep learning SEP

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [9]:
preprocess_text['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [10]:
preprocess_text['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[  101,  1045,  2066, 18750,  4730,   102,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [11]:
bert_model_url=hub.KerasLayer(model_url)

In [12]:
bert_model_results=bert_model_url(preprocess_text)

In [13]:
bert_model_results.keys()

dict_keys(['default', 'encoder_outputs', 'sequence_output', 'pooled_output'])

In [14]:
bert_model_results['default']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.9204047 , -0.520073  , -0.83385944, ..., -0.7037315 ,
        -0.69518185,  0.9268696 ],
       [-0.8240753 , -0.2740935 ,  0.32880172, ...,  0.09023435,
        -0.5935006 ,  0.80685514],
       [-0.6890903 , -0.15622042,  0.7336852 , ...,  0.40575954,
        -0.5044205 ,  0.7672048 ]], dtype=float32)>

In [15]:
bert_model_results['encoder_outputs']

[<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
 array([[[ 0.1680596 , -0.04068397, -0.0973766 , ..., -0.01585863,
           0.1246638 ,  0.00385819],
         [ 0.62237984,  0.8589635 , -0.26993302, ...,  0.6237664 ,
           1.0031265 ,  0.17689186],
         [ 0.19485795,  1.0003849 ,  0.62874126, ..., -0.06815147,
           0.8775    , -0.01461313],
         ...,
         [ 0.16032578, -0.21716091,  0.61941653, ..., -0.23219061,
          -0.17554078,  0.22784513],
         [ 0.05949733, -0.22536327,  0.46455365, ..., -0.20262428,
          -0.07578523,  0.14909586],
         [ 0.21300925, -0.15640727,  0.5415452 , ...,  0.2370207 ,
          -0.37317204,  0.06312768]],
 
        [[ 0.17131856, -0.01582628, -0.06446777, ...,  0.05657907,
           0.03254997,  0.06062255],
         [-0.5894119 ,  0.3403703 , -0.01000333, ..., -0.09194256,
           0.6389289 ,  0.00562882],
         [-1.0902737 , -0.46204144, -0.5030287 , ...,  0.01006795,
           0.44670707,  0.52

In [16]:
bert_model_results['sequence_output']

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[ 0.01944783,  0.29181808, -0.31138718, ..., -0.10158004,
          0.21108842,  0.7088622 ],
        [ 0.31351686,  0.26346898, -0.48046392, ...,  0.20941867,
          0.55649567,  0.343432  ],
        [ 0.19312124,  0.78480047,  0.57387924, ...,  0.4041856 ,
          0.11000222,  0.30479515],
        ...,
        [ 0.13689516,  0.06780405,  0.37204862, ...,  0.08540495,
         -0.12744081,  0.25802973],
        [ 0.04380764,  0.23566094,  0.35952055, ...,  0.01607911,
         -0.01862604,  0.32013118],
        [-0.11117852, -0.23925062,  0.20836425, ...,  0.13099945,
         -0.13647947,  0.09490357]],

       [[ 0.02533172,  0.02196816, -0.00307716, ..., -0.02822019,
          0.14845884,  0.3568924 ],
        [-0.3515517 , -0.4349348 , -0.5464882 , ..., -0.2808312 ,
          0.8692118 ,  0.23329704],
        [-0.54836494, -0.60499686,  0.14020488, ..., -0.14339273,
          0.22427759,  0.52897334],
        ...,

In [17]:
bert_model_results['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.9204047 , -0.520073  , -0.83385944, ..., -0.7037315 ,
        -0.69518185,  0.9268696 ],
       [-0.8240753 , -0.2740935 ,  0.32880172, ...,  0.09023435,
        -0.5935006 ,  0.80685514],
       [-0.6890903 , -0.15622042,  0.7336852 , ...,  0.40575954,
        -0.5044205 ,  0.7672048 ]], dtype=float32)>