# Numpy Exercise

In [ ]:
import numpy as np
import pandas as pd

**1**

In [ ]:
# 1. Create a vector of size 10
#   1.1 Fill all the elements with zeros, print the result

myvector = np.array([0,0,0,0,0,0,0,0,0,0])
print(myvector) 

[0 0 0 0 0 0 0 0 0 0]


In [ ]:
#  1.2 Assign a value of “1” to the fifth value in this vector. Print the result.

myvector = np.array([0,0,0,0,1,0,0,0,0,0])
print(myvector)

[0 0 0 0 1 0 0 0 0 0]


**2**


In [ ]:
# 2. Create a vector with values ranging from 1 to 20 inclusive 
#    2.1 Print th#e result

myvector = np.arange(1,21,1)
print(myvector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# 2.2 Reverse the vector then print the result

myvector = np.arange(20,0,-1)
print(myvector)

[20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]


**3**


In [ ]:
# 3. Create a random vector of size 50.
# 3.1 Print the vector

myvector = np.random.randint(0,50,50)
print(myvector)

[22 26 41 10 38 10 15 37 46 37 46 44  2  8 45 15 42 18 45 33 28  0 33 42
  2 20  8 31  0  4  7  2 43  7 14 28 35  8  4 20 29 43 30 34  5  5 38 49
 30 20]


In [ ]:
# 3.2 Find the mean of the vector and print the result
myvector = np.random.randint(0,50,50)
print(myvector)
myvector_mean= np.mean(myvector)
print("mean is", myvector_mean)



[ 7 44 24  3 36 29  6 45 29 49 27 18 37 22 20 43 30  7 10  7 14 45 40 36
 46 35 29 44 37 25  1 18 34 43  4 30  8 12 14 47 15 26 41 13 30 33 42 42
 30 41]
mean is 27.36


**4**

In [ ]:
# 4 Create a 3x4 matrix with a value of “1” for each element. Print the result.

mymatrix_1= np.array([
                    [1,1,1,1]
                    ,[1,1,1,1]
                    ,[1,1,1,1]
                    ])
print(mymatrix_1)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
# 4.1 Create a 4x2 matrix with a value of “1” for each element. Print the result.

mymatrix_2= np.array([
                    [1,1]
                    ,[1,1]
                    ,[1,1]
                    ,[1,1]
                    ])
print(mymatrix_2)

[[1 1]
 [1 1]
 [1 1]
 [1 1]]


In [ ]:
# Multiply both 3x4 and 4x3 matrix and print the final result

matrix_mul = np.matmul(mymatrix_1,mymatrix_2)
print(matrix_mul)

[[4 4]
 [4 4]
 [4 4]]


**5**

In [ ]:
# 5 Create a 5x5 array with random numbers, print the array

myrandom_array = np.random.rand(5,5)
print(myrandom_array)

[[0.9765059  0.56445829 0.56295723 0.56219188 0.69982572]
 [0.41005734 0.86165677 0.40190369 0.95190188 0.1393765 ]
 [0.15490944 0.71489437 0.43632701 0.0351991  0.07873564]
 [0.97881319 0.1911054  0.69080167 0.54912793 0.83666721]
 [0.64715114 0.13184502 0.30948482 0.67541355 0.95447704]]


In [ ]:
# 5.1 Find the min value from this array, print the result

myrandom_array = np.random.rand(5,5)
print(myrandom_array)
min_value = np.amin(myrandom_array)
print("Min value", min_value)

[[0.9570099  0.9535161  0.77517494 0.69578304 0.72860505]
 [0.24879719 0.95672152 0.52657699 0.44697029 0.17512435]
 [0.38382936 0.60093912 0.83217348 0.80377567 0.63975297]
 [0.62253662 0.65181288 0.59065821 0.18960417 0.77800361]
 [0.03431476 0.47844648 0.81302757 0.82905876 0.29468141]]
Min value 0.03431475723290589


In [ ]:
# 5.2 Find the max value from this array, print the result

myrandom_array = np.random.rand(5,5)
max_value = np.amax(myrandom_array)
print(myrandom_array)
print("Max value", max_value)

[[0.89587587 0.32201426 0.04652754 0.59559136 0.17850864]
 [0.77822617 0.44177371 0.66377833 0.75638907 0.34137956]
 [0.07719869 0.32213319 0.6615218  0.69482709 0.55574758]
 [0.76932938 0.8240934  0.04894999 0.41941824 0.47360648]
 [0.47366393 0.38001327 0.08623229 0.23770089 0.96639109]]
Max value 0.9663910858542508


# Pandas Exercise

**1**

In [ ]:
# 1 Create a Panda Series from 10 to 50 in multiples of 10. Print the series.

import numpy as np
import pandas as pd
myarray = np.array([10,20,30,40,50])
myseries = pd.Series(myarray)
print(myseries)

0    10
1    20
2    30
3    40
4    50
dtype: int64


**2**

In [ ]:
# 2 Create a dictionary of weekdays and print this as panda series.

# Example {“Monday”:1, “Tuesday:2 etc..}


myweekday = pd.DataFrame([['Monday',1], ['Tuesday',2], ['Wednesday',3], ['Thursday',4],['Friday',5],['Saturday',6],['Sunday',7]] )
#print(myweekday)
#print("       ")
print(dict(myweekday.values))


{'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6, 'Sunday': 7}


**3**

In [ ]:
# 3 Create a data frame in Pandas with Months of the calendar year. 
#  Your output should appear like this

#  Name         Month
#  January        1
#  February       2
#  March          3
#  ….             ..
#  ….             ..


data_columns = ["Name","Month"]
myarray1 = pd.DataFrame([['January',1], ['February',2], ['March',3], ['April',4],['May',5],['June',6],['July',7],['August',8],['September',9],['October',10],['November',11],['December',12]],columns=data_columns )
print(myarray1)


         Name  Month
0     January      1
1    February      2
2       March      3
3       April      4
4         May      5
5        June      6
6        July      7
7      August      8
8   September      9
9     October     10
10   November     11
11   December     12


**4**

In [ ]:
# 4.1 Use this input data and create a dataframe. Print the dataframe

# input = [{'Name':'Monday', 'day':1},

#       {'Name':'Tuesday', 'day':2},

#       {'Name':'Wednesday', 'day':3},

#       {'Name':'Thursday', 'day':4},

#       {'Name':'Friday', 'day':5},

#       {'Name':'Saturday', 'day':6},

#       {'Name':'Sunday', 'day':7},

#       ]

# Next, iterate over this data frame and print the results.

data_columns = ["Name","day"]
myweekday = pd.DataFrame([['Monday',1], ['Tuesday',2], ['Wednesday',3], ['Thursday',4],['Friday',5],['Saturday',6],['Sunday',7]],columns=data_columns )

#print(myweekday)
#print("       ")

print((myweekday))


        Name  day
0     Monday    1
1    Tuesday    2
2  Wednesday    3
3   Thursday    4
4     Friday    5
5   Saturday    6
6     Sunday    7


In [ ]:
# 4.2 Next, iterate over this data frame and print the results.
for index, row in myweekday.iterrows():
    print(row['Name'], row['day'])

Monday 1
Tuesday 2
Wednesday 3
Thursday 4
Friday 5
Saturday 6
Sunday 7


**5**

In [ ]:
# 5. Create a numpy array with 5 elements of your choice. Index these elements in Panda series and print the series.

myarray = np.array([10,20,30,40,50])
myPandaSeries=pd.Series(myarray)
print(myPandaSeries)


0    10
1    20
2    30
3    40
4    50
dtype: int64
